SELECT
    event_key
    ,event_date
    ,event_time
    ,event_status
    ,event_winner
    ,event_first_player
    ,first_player_key
    ,event_second_player
    ,second_player_key
    ,tournament_sourface
    ,tournament_name
    ,event_type
    ,event_type_2
    ,event_type_3
    ,event_type_type
    ,event_gender
    ,p1_wins_sourface
    ,p1_losses_sourface
    ,p1_wins_all
    ,p1_losses_all
    ,p1_rend_all
    ,p1_rend_sup
    ,p1_points
    ,p2_wins_sourface
    ,p2_losses_sourface
    ,p2_wins_all
    ,p2_losses_all
    ,p2_rend_all
    ,p2_rend_sup
    ,p2_points
    ,p1_wins_h2h
    ,p1_perc_h2h
    ,p2_wins_h2h
    ,p2_perc_h2h
    ,p1_odds
    ,p2_odds
    ,event_first_player_logo
    ,event_second_player_logo
    ,load_timestamp
FROM tenis_api.main_todays_games_details
order by event_date, event_time;
